<?php


namespace App\Managers;

use App\Models\api\v1\person\PersonModel;
use App\Repositories\api\v1\ticket\PersonRepository;
use Freelabois\LaravelQuickstart\Extendables\ManipulationManager;

class PersonManager extends ManipulationManager
{

    protected $validation = [
        self::CREATE => [],
        self::EDIT => []
    ];

    /**
     * @var PersonRepository
     */
    protected $repository;

    public function __construct(PersonRepository $repository)
    {
        $this->repository = $repository;
    }

    public function storeOrUpdate($values, int $id = null, $relations = [])
    {
        if(!isset($values["per_status"]) || empty($values["per_status"])){
            $values["per_status"] = PersonModel::STATUS_ATIVO;
        }
        return parent::storeOrUpdate($values, $id, $relations); // TODO: Change the autogenerated stub
    }

}
